-- Create the table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.analytics_events (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add columns if they don't exist
ALTER TABLE public.analytics_events ADD COLUMN IF NOT EXISTS event_type text;
ALTER TABLE public.analytics_events ADD COLUMN IF NOT EXISTS event_name text;
ALTER TABLE public.analytics_events ADD COLUMN IF NOT EXISTS user_id uuid references auth.users(id);
ALTER TABLE public.analytics_events ADD COLUMN IF NOT EXISTS session_id text;
ALTER TABLE public.analytics_events ADD COLUMN IF NOT EXISTS page_path text;
ALTER TABLE public.analytics_events ADD COLUMN IF NOT EXISTS referrer text;
ALTER TABLE public.analytics_events ADD COLUMN IF NOT EXISTS device_type text;
ALTER TABLE public.analytics_events ADD COLUMN IF NOT EXISTS browser text;
ALTER TABLE public.analytics_events ADD COLUMN IF NOT EXISTS country text;
ALTER TABLE public.analytics_events ADD COLUMN IF NOT EXISTS data jsonb;

-- Indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_analytics_events_created_at ON public.analytics_events(created_at);
CREATE INDEX IF NOT EXISTS idx_analytics_events_event_type ON public.analytics_events(event_type);
CREATE INDEX IF NOT EXISTS idx_analytics_events_session_id ON public.analytics_events(session_id);

-- Enable RLS
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

-- Policies

-- Allow anonymous and authenticated users to insert events
DROP POLICY IF EXISTS "Enable insert for all users" ON public.analytics_events;
CREATE POLICY "Enable insert for all users" ON public.analytics_events FOR INSERT TO public WITH CHECK (true);

-- Allow admins (or service role) to read
-- Note: Service role always has full access. 
-- We add a policy for authenticated users to read just in case the dashboard uses a non-service client,
-- but typically analytics data should be restricted.
-- For now, we'll assume the backend uses service role for reading.
